// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SorApi.Context;

#nullable disable

namespace SorApi.Migrations
{
    [DbContext(typeof(SorDbContext))]
    [Migration("20230102125535_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SorApi.Model.SorModel", b =>
                {
                    b.Property<string>("SorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnvironMentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SorId");

                    b.ToTable("Sors");
                });
#pragma warning restore 612, 618
        }
    }
}
