// <auto-generated />
using EnvironMentApi.context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnvironMentApi.Migrations
{
    [DbContext(typeof(EnvironMentDbContext))]
    [Migration("20230102125442_inttial")]
    partial class inttial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnvironMentApi.Model.EnviornmentModel", b =>
                {
                    b.Property<string>("EnvironMentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EnvironMentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnvironMentId");

                    b.ToTable("Enviornments");
                });
#pragma warning restore 612, 618
        }
    }
}
